project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - /src/executive_summary.qmd
    - /src/all_counties_summary.qmd
    - /src/kilifi.qmd
    - /src/kirinyaga.qmd
    - /src/kisumu.qmd
    - /src/turkana.qmd

  preview:
    port: 230

website:
  title: "Kenya County PCRA"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - /src/executive_summary.qmd
      - /src/all_counties_summary.qmd
      - /src/kilifi.qmd
      - /src/kirinyaga.qmd
      - /src/kisumu.qmd
      - /src/turkana.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - /src/executive_summary.qmd
      - /src/all_counties_summary.qmd
      - /src/kilifi.qmd
      - /src/kirinyaga.qmd
      - /src/kisumu.qmd
      - /src/turkana.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

callout-appearance: simple

execute:
  freeze: auto # to ensure R code is only executed locally

editor: visual
